version: "3.8"
volumes:
  shared-secrets:
    driver: local
  execution-node-data:
    driver: local
  beacon-node-data:
    driver: local
networks:
  ethereum-validator:
services:
  execution-node:
    image: ethereum/client-go:alltools-stable
    ports:
      - "30303:30303"
    volumes:
      - execution-node-data:/root/.ethereum
      - shared-secrets:/root/secrets
    command: geth --holesky --authrpc.addr execution-node --authrpc.port 8551 --authrpc.vhosts execution-node --http --http.api eth,net,engine,admin --authrpc.jwtsecret /root/secrets/jwt.hex
  beacon-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    ports:
      - "4000:4000"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - beacon-node-data:/data
      - shared-secrets:/root/secrets
    command:
      - --accept-terms-of-use
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --execution-endpoint=http://execution-node:8551
      - --jwt-secret=/root/secrets/jwt.hex
      - --checkpoint-sync-url=https://holesky.beaconstate.info
      - --genesis-beacon-api-url=https://holesky.beaconstate.info
      - --suggested-fee-recipient=${SUGGESTED_FEE_RECIPIENT}
      - --holesky
    depends_on:
      - execution-node
