volumes:
  shared-secrets:
    driver: local
  execution-node-data:
    driver: local
  beacon-node-data:
    driver: local
  validator-node-data:
    driver: local
  validator-wallet:
    driver: local
networks:
  ethereum-validator:
services:
  execution-node:
    image: ethereum/client-go:alltools-stable
    restart: unless-stopped
    ports:
      - "30303:30303"
    volumes:
      - execution-node-data:/root/.ethereum
      - shared-secrets:/root/secrets
    command:
      - geth
      - --holesky
      - --authrpc.addr execution-node
      - --authrpc.port 8551
      - --authrpc.vhosts execution-node
      - --http --http.api eth,net,engine,admin
      - --authrpc.jwtsecret /root/secrets/jwt.hex

  beacon-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    restart: unless-stopped
    ports:
      - "13000:13000/tcp"
      - "12000:12000/udp"
    volumes:
      - beacon-node-data:/data
      - shared-secrets:/root/secrets
    command:
      - --holesky
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --execution-endpoint=http://execution-node:8551
      - --jwt-secret=/root/secrets/jwt.hex
      - --checkpoint-sync-url=${BEACON_API_URL}
      - --genesis-beacon-api-url=${BEACON_API_URL}
      - --suggested-fee-recipient=${SUGGESTED_FEE_RECIPIENT}
      - --accept-terms-of-use
    depends_on:
      - execution-node

  validator-node:
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    restart: unless-stopped
    volumes:
      - validator-node-data:/validatorDB
      - validator-wallet:/wallet
    command:
      - --beacon-rpc-provider=beacon-node:4000
      - --wallet-dir=/wallet
      - --datadir=/validatorDB
      - --suggested-fee-recipient=${SUGGESTED_FEE_RECIPIENT}
      - --accept-terms-of-use
    depends_on:
      - execution-node
      - beacon-node

  validator-import:
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    profiles: ["import-keys"]
    volumes:
      - ./validator_keys:/keys
      - validator-wallet:/wallet
    command: accounts import --keys-dir=/keys --wallet-dir=/wallet --accept-terms-of-use
